# Generated by Django 2.2.5 on 2019-09-19 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('camid', models.IntegerField(db_column='camId', primary_key=True, serialize=False)),
                ('scenicid', models.IntegerField(db_column='scenicId')),
                ('camplace', models.CharField(blank=True, db_column='camPlace', max_length=255, null=True)),
            ],
            options={
                'db_table': 'camera',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Recordnums',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scenicid', models.IntegerField(db_column='scenicId')),
                ('camid', models.IntegerField(blank=True, db_column='camId', null=True)),
                ('nums', models.IntegerField(blank=True, null=True)),
                ('year', models.IntegerField()),
                ('month', models.IntegerField(blank=True, null=True)),
                ('day', models.IntegerField(blank=True, null=True)),
                ('hour', models.IntegerField(blank=True, null=True)),
                ('minute', models.IntegerField(blank=True, null=True)),
                ('sec', models.IntegerField(blank=True, null=True)),
                ('createat', models.CharField(blank=True, db_column='createAt', max_length=255, null=True)),
            ],
            options={
                'db_table': 'recordnums',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Recordwarnings',
            fields=[
                ('warningid', models.AutoField(db_column='warningId', primary_key=True, serialize=False)),
                ('scenicid', models.IntegerField(blank=True, db_column='scenicId', null=True)),
                ('level', models.IntegerField(blank=True, null=True)),
                ('createat', models.CharField(blank=True, db_column='createAt', max_length=255, null=True)),
            ],
            options={
                'db_table': 'recordwarnings',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Scenic',
            fields=[
                ('scenicid', models.IntegerField(db_column='scenicId', primary_key=True, serialize=False)),
                ('scenicname', models.CharField(blank=True, db_column='scenicName', max_length=255, null=True)),
                ('warning1nums', models.IntegerField(blank=True, db_column='warning1Nums', null=True)),
                ('warning2nums', models.IntegerField(blank=True, db_column='warning2Nums', null=True)),
                ('warning3nums', models.IntegerField(blank=True, db_column='warning3Nums', null=True)),
            ],
            options={
                'db_table': 'scenic',
                'managed': False,
            },
        ),
    ]
