# Generated by Django 2.2.5 on 2019-09-20 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('camid', models.CharField(db_column='camId', max_length=11, primary_key=True, serialize=False)),
                ('camplace', models.CharField(blank=True, db_column='camPlace', max_length=255, null=True)),
                ('camlgn', models.FloatField(blank=True, db_column='camLgn', null=True)),
                ('camlat', models.FloatField(blank=True, db_column='camLat', null=True)),
            ],
            options={
                'db_table': 'camera',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Recordwarnings',
            fields=[
                ('warningid', models.AutoField(db_column='warningId', primary_key=True, serialize=False)),
                ('scenicid', models.CharField(blank=True, db_column='scenicId', max_length=11, null=True)),
                ('camid', models.CharField(blank=True, db_column='camId', max_length=11, null=True)),
                ('level', models.IntegerField(blank=True, null=True)),
                ('type', models.IntegerField(blank=True, null=True)),
                ('createat', models.CharField(blank=True, db_column='createAt', max_length=255, null=True)),
            ],
            options={
                'db_table': 'recordwarnings',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Scenic',
            fields=[
                ('scenicid', models.CharField(db_column='scenicId', max_length=11, primary_key=True, serialize=False)),
                ('scenicname', models.CharField(blank=True, db_column='scenicName', max_length=255, null=True)),
                ('warning1nums', models.IntegerField(blank=True, db_column='warning1Nums', null=True)),
                ('warning2nums', models.IntegerField(blank=True, db_column='warning2Nums', null=True)),
                ('warning3nums', models.IntegerField(blank=True, db_column='warning3Nums', null=True)),
                ('lgn', models.FloatField(blank=True, null=True)),
                ('lat', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'scenic',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Recordnums',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nums', models.IntegerField(blank=True, null=True)),
                ('year', models.IntegerField()),
                ('month', models.IntegerField(blank=True, null=True)),
                ('day', models.IntegerField(blank=True, null=True)),
                ('hour', models.IntegerField(blank=True, null=True)),
                ('minute', models.IntegerField(blank=True, null=True)),
                ('sec', models.IntegerField(blank=True, null=True)),
                ('createat', models.CharField(blank=True, db_column='createAt', max_length=255, null=True)),
                ('camid', models.ForeignKey(blank=True, db_column='camId', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='capacityWeb.Camera')),
                ('scenicid', models.ForeignKey(db_column='scenicId', on_delete=django.db.models.deletion.DO_NOTHING, to='capacityWeb.Scenic')),
            ],
            options={
                'db_table': 'recordnums',
            },
        ),
    ]
