# Generated by Django 2.2.5 on 2019-11-22 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capacityWeb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.PositiveSmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Mobile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('todaydividual', models.CharField(blank=True, db_column='todayDividual', max_length=255, null=True)),
                ('todayteam', models.CharField(blank=True, db_column='todayTeam', max_length=255, null=True)),
                ('todaytotal', models.CharField(blank=True, db_column='todayTotal', max_length=255, null=True)),
                ('centerdividual', models.CharField(blank=True, db_column='centerDividual', max_length=255, null=True)),
                ('centerteam', models.CharField(blank=True, db_column='centerTeam', max_length=255, null=True)),
                ('centerin', models.CharField(blank=True, db_column='centerIn', max_length=255, null=True)),
                ('eastsouthdividual', models.CharField(blank=True, db_column='eastsouthDividual', max_length=255, null=True)),
                ('eastsouthteam', models.CharField(blank=True, db_column='eastsouthTeam', max_length=255, null=True)),
                ('eastsouthin', models.CharField(blank=True, db_column='eastSouthIn', max_length=255, null=True)),
                ('ticketdate', models.CharField(blank=True, db_column='ticketDate', max_length=255, null=True)),
            ],
            options={
                'db_table': 'mobile',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Wifi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scenicid', models.CharField(blank=True, db_column='scenicId', max_length=11, null=True)),
                ('camid', models.CharField(blank=True, db_column='camId', max_length=11, null=True)),
                ('apcn', models.CharField(blank=True, max_length=255, null=True)),
                ('stamac', models.CharField(blank=True, db_column='staMac', max_length=255, null=True)),
                ('tertype', models.CharField(blank=True, db_column='terType', max_length=255, null=True)),
                ('vendorcn', models.CharField(blank=True, db_column='vendorCn', max_length=255, null=True)),
                ('starxbytes', models.CharField(blank=True, db_column='staRxbytes', max_length=255, null=True)),
                ('statxbytes', models.CharField(blank=True, db_column='staTxbytes', max_length=255, null=True)),
                ('year', models.CharField(max_length=255)),
                ('month', models.CharField(blank=True, max_length=255, null=True)),
                ('day', models.CharField(blank=True, max_length=255, null=True)),
                ('hour', models.CharField(blank=True, max_length=255, null=True)),
                ('minute', models.CharField(blank=True, max_length=255, null=True)),
                ('createat', models.CharField(blank=True, db_column='createAt', max_length=255, null=True)),
            ],
            options={
                'db_table': 'wifi',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='recordnums',
            options={'managed': False},
        ),
    ]
