# Generated by Django 2.2.5 on 2019-11-25 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capacityWeb', '0003_wifiinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Camerainfo',
            fields=[
                ('cameraid', models.IntegerField(db_column='cameraId', primary_key=True, serialize=False)),
                ('sciencid', models.IntegerField(db_column='sciencId')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('state', models.CharField(blank=True, max_length=255, null=True)),
                ('adminid', models.IntegerField(blank=True, db_column='adminId', null=True)),
                ('adminname', models.CharField(blank=True, db_column='adminName', max_length=255, null=True)),
                ('devicetype', models.CharField(blank=True, db_column='deviceType', max_length=255, null=True)),
            ],
            options={
                'db_table': 'camerainfo',
                'managed': False,
            },
        ),
    ]
